services:

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: